[[pages]]
path = "pages/home.py"
name = "ĞĞ¿Ğ¸ÑĞ°Ğ½Ğ¸Ğµ"
icon = "ğŸ "

[[pages]]
name = "ĞĞºĞºĞ°ÑƒĞ½Ñ‚"
icon = "ğŸ‘¤"
is_section = true

[[pages]]
path = "pages/user/login.py"
name = "Ğ’Ñ…Ğ¾Ğ´"
icon = "ğŸ‘¤"

[[pages]]
path = "pages/user/registration.py"
name = "Ğ ĞµĞ³Ğ¸ÑÑ‚Ñ€Ğ°Ñ†Ğ¸Ñ"
icon = "ğŸ‘¤"

[[pages]]
path = "pages/user/account.py"
name = "Ğ˜Ğ½Ñ„Ğ¾Ñ€Ğ¼Ğ°Ñ†Ğ¸Ñ"
icon = "ğŸ‘¤"

[[pages]]
path = "pages/user/logout.py"
name = "Ğ’Ñ‹Ñ…Ğ¾Ğ´"
icon = "ğŸ‘¤"

[[pages]]
name = "ĞœĞ¾Ğ´ĞµĞ»Ğ¸"
icon = "âœ¨"
is_section = true

[[pages]]
path = "pages/model/model_train.py"
name = "ĞĞ±ÑƒÑ‡ĞµĞ½Ğ¸Ğµ"
icon = "ğŸ“"

[[pages]]
path = "pages/model/model_info.py"
name = "Ğ˜Ğ½Ñ„Ğ¾Ñ€Ğ¼Ğ°Ñ†Ğ¸Ñ"
icon = "ğŸ“š"

[[pages]]
name = "Ğ˜Ğ·Ğ¾Ğ±Ñ€Ğ°Ğ¶ĞµĞ½Ğ¸Ñ"
icon = "âœ¨"
is_section = true

[[pages]]
path = "pages/image/classification.py"
name = "ĞšĞ»Ğ°ÑÑĞ¸Ñ„Ğ¸ĞºĞ°Ñ†Ğ¸Ñ"
icon = "ğŸ”"

[[pages]]
path = "pages/image/load.py"
name = "Ğ—Ğ°Ğ³Ñ€ÑƒĞ·ĞºĞ°"
icon = "ğŸ”"

[[pages]]
path = "pages/image/approve.py"
name = "ĞŸĞ¾Ğ´Ñ‚Ğ²ĞµÑ€Ğ¶Ğ´ĞµĞ½Ğ¸Ğµ"
icon = "âœ”ï¸"